name = "Goblins"
author = "Martin Page"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a4e27b9e169940169c30c649f1bf29586c162e6273892c0d5de5a04642de6a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
