name = "Goblins"
author = "Martin Page"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de4828a4f4215dcb41c5a779defb06fadc37a143239b6fa4a0dfe687178f9ede"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
