name = "Goblins"
author = "Martin Page"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bc673a6f397379d7aa9c3eceddddb52ca1332fe6c356635ce2b3c3be416e78a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
